@startuml
title Diagrama de Casos de Uso
Sistema POS — Bar Carrefour

left to right direction

actor "Encargada" as ENC
actor "Dueño" as DUE
actor "Proveedor de Pago" as PAG

rectangle "Sistema POS Bar Carrefour" {
  usecase "Autenticar usuario" as UC0
  usecase "Registrar pedido" as UC1
  usecase "Consultar disponibilidad\nde stock" as UC2
  usecase "Procesar pago" as UC3
  usecase "Reponer stock\na demanda" as UC4
  usecase "Emitir ticket" as UC5
  usecase "Consultar historial\nde ventas" as UC6
}

ENC --> UC1
ENC --> UC4
PAG --> UC3
DUE --> UC6

UC1 .> UC0 : <<include>>
UC1 .> UC2 : <<include>>
UC6 .> UC0 : <<include>>

UC3 .> UC1 : <<extend>>
UC4 .> UC2 : <<extend>>
UC5 .> UC3 : <<extend>>

@enduml