@startuml

title Modelo Entidad-Relación - Sistema POS Bar Carrefour

entity Usuario {
    * id_usuario : INT <<PK>>
    --
    nombre : VARCHAR
    usuario : VARCHAR
    contraseña : VARCHAR
    rol : VARCHAR
}

entity Mesa {
    * id_mesa : INT <<PK>>
    --
    numero_mesa : INT
    estado : VARCHAR
}

entity Pedido {
    * id_pedido : INT <<PK>>
    --
    fecha : DATETIME
    subtotal : DECIMAL
    id_mesa : INT <<FK>>
    id_usuario : INT <<FK>>
}

entity Detalle_Pedido {
    * id_detalle : INT <<PK>>
    --
    cantidad : INT
    subtotal : DECIMAL
    id_pedido : INT <<FK>>
    id_producto : INT <<FK>>
}

entity Producto {
    * id_producto : INT <<PK>>
    --
    nombre : VARCHAR
    precio : DECIMAL
    stock : INT
}

entity Pago {
    * id_pago : INT <<PK>>
    --
    metodo_pago : VARCHAR
    total : DECIMAL
    fecha : DATETIME
    id_pedido : INT <<FK>>
}

entity Ticket {
    * id_ticket : INT <<PK>>
    --
    fecha_emision : DATETIME
    id_pago : INT <<FK>>
}

Usuario ||--o{ Pedido : registra
Mesa ||--o{ Pedido : tiene
Pedido ||--|{ Detalle_Pedido : contiene
Producto ||--o{ Detalle_Pedido : corresponde
Pedido ||--|| Pago : genera
Pago ||--|| Ticket : emite

@enduml